### ISSUE TITLE
Data for utility rooms

### ISSUE THREAD

**Issue by DIProgan** [miketrethewey/sm-json-data#152]
There's no data for various purposes that a room/node could have such as save, energy/missile refill or map station. Farming spots could possibly go in the same object.

**Comment by fdtaillefer** [comment]
There's a chance regular old nodes with new types could do the trick here.

**Comment by DIProgan** [comment]
"nodeType": "utility",
"nodeSubType": "save/missile/energy/farming"
How about it?

**Comment by DIProgan** [comment]
On further considerations I think all of these should be part of existing nodes where possible

```json
"id": 1,
          "name": "Left Door",
          "nodeType": "door",
          "nodeSubType": "blue",
          "utility": [ "farming" ],
```

**Comment by fdtaillefer** [comment]
I'm not a fan of the `farming` utility. I'd rather put down a spawner with the enemy type and the amount that spawns which you can resonably farm at once. Then logic algorithms can decide themselves whether farming a given resource at that spawner is reasonable or not.

I can go with the rest. The ship is a compelling reason to put utility on nodes rather than as nodes. And if we really need to make a node for something, it can be a junction.

**Comment by DIProgan** [comment]
Yeah I figured farming was going to be a maybe. I'll just have utility point towards the farm spots we have until a future solution. Ship needs another utility type now though since I made it use farming in lack of something that gave full of everything. ``maxEverything``` ?

**Comment by fdtaillefer** [comment]
We could also do all refills separately. In which case we'd need to add supers, power bombs, and reserve tanks to the ship.

**Comment by DIProgan** [comment]
I can see all the ammo and health types go into it. Sounds fine. As for differentiating energy from reserve I think it's already pretty divided? Energy is used all round the place, for room names and so on even if reserves are not filled there so I don't know what a better name would be.

**Comment by fdtaillefer** [comment]
Yeah I guess reserves not refilling at health refills is just a thing you have to know.
