### ISSUE TITLE
Represent multi-drop enemies

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#206]
Some enemies drop more than one drop off their drop table when they die. This includes at least:
- Most bosses
- Metroids
- Metal pirates
- Mini Kraid

There is also Kagos which in their own way lead to many drops. Should those Kago spawns have their own name? Do they have their own drop table? How many of them do you get per Kago? Should we just put them in a room alongside the Kagos?

We should find a way ti represent all of those.

**Comment by DIProgan** [comment]
Drop data:
Geruta 1 (2 using PB)
Magdollite 1 (2 using PB)
Mini Kraid: 5
Metal Pirates: 6
Metroids: 6 (1 using PB)
Crocomire: 11
Spore Spawn: 12
Bomb Torizo: 16
Golden Torizo: 16
Draygon: 16
Kraid: 16
Phantoon: 16
Ridley: 16
Kago: Always takes 11 hits regardless of weapon. Gnats disappear if they hit you (20/10/5). Kago's droptable is likely the same as the gnats.

"The amount of items that certain enemies will drop changes depending on how they are killed. For example, if you destroy a Geruta, a Magdollite, and a Metroid with a Power Bomb, they will drop up to two items, three items, and one item (instead of up to one item, one item, and six items) respectively. These are the only cases of death via a Power Bomb causing a different amount of drops than the typical amount." 
https://wiki.supermetroid.run/Enemies#How_Drops_Work
