### ISSUE TITLE
Moat PB boost strat

### ISSUE THREAD

**Issue by fdtaillefer** [miketrethewey/sm-json-data#311]
See https://youtu.be/TS5KB3I-SWU

**Comment by osse101** [comment]
This starts on the missile pedestal.  Do a CWJ into a bomb boost to reach either door.  Actually regular CWJ probably overrules this since it has fewer reqs.  Regular CWJ is at speed so you have a small jump window but in this case with the water a slow cwj is also a low frame window jump.

Infinite ceiling bomb jump can be used to get from door to door.

Diagonal bomb jumps while different is really just a harder version of HBJ

**Comment by kjbranch** [comment]
The originally shared video link is broken, does anyone have a clip for it or know what the strat was?
