### ISSUE TITLE
Add left facing door X-Ray climbs

### ISSUE THREAD

**Issue by osse101** [miketrethewey/sm-json-data#410]
Getting doorstuck on left facing doors has slightly different inputs than the existing xray climb tech, dashing stationary spinjump into doorcheck, then hold down.  https://youtu.be/o221jdmsxq8

Here's a partially confirmed list of where these xray climbs can be used.  

- Eticoon lobby upper grey
- Mission Impossible lower (exit)
- big pink <- green hills entrance
- below spazer
- tube save station
- mini kraid entrance
- crumble shaft
- screw attack refill door
- maridia map door
- right sand pit toilet door
- right door left leg pants room
- below aqueduct supers
- bowling farm entrance

Some doors, like right side landing site, are not included because the terrain geometry is unsuitable for xray climbing.

**Comment by fdtaillefer** [comment]
I think we'll want separate techs for this, and the existing tech can probably stand to be renamed for clarity.

The list above translates to the following links:

- _Eticoon lobby upper grey_:  Green Brinstar Main Shaft / Etecoon Room, node 7 to 12. NOTE: The x-ray climb at the bottom left does not work because it's configured to start at 13 rather than 8, that's incompatible with `mustStayPut`. I should fix this as well and adjust the diagram.
- _Mission Impossible lower (exit)_: Pink Brinstar Power Bomb Room, node 2 to 1.
- _big pink <- green hills entrance_: Big Pink, node 8 to 13.
- _below spazer_: Below Spazer, node 2 to 3.
- _tube save station_: Glass Tunnel, node 2 to 3
- _mini kraid entrance_: Doesn't really do anything, I would skip this
- _crumble shaft_: Crumble Shaft, node 2 to 1
- screw attack refill door: Screw Attack Room, node 2 to 3
- _maridia map door_: Crab Hole, node 3 to 4
- _right sand pit toilet door_: Oasis, node 2 to 6. NOTE: The x-ray climb on the left does not work because it's configured to start at 5 rather than 1, that's incompatible with `mustStayPut`. I should fix this as well and adjust the diagram.
- _right door left leg pants room_: Pants Room, node 3 to 2. NOTE: The x-ray climb on the left does not work because it's configured to start at 5 rather than 1, that's incompatible with `mustStayPut`. I should fix this as well and adjust the diagram.
- _below aqueduct supers_: Aqueduct, node 5 to 8.
- _bowling farm entrance_: West Ocean, node 6 to 12.

**Comment by fdtaillefer** [comment]
Reorganized X-Ray climb techs in #414. A byproduct of that work was that Bowling Skip was fixed to no longer require `canStationarySpinjump`. Some strats were renamed for clarity vs. forthcoming left-facing door X-Ray climbs.

There is still an issue with the interaction of `resetRoom` and door-based X-Ray climbs that must be resolved before work on this can begin in earnest.

**Comment by fdtaillefer** [comment]
Between #418 and #419, the issue with (a small amount of) door-based X-Ray climbs is fixed and the room diagrams are also up-to-date.

Even when links to and from a door node all passed through a junction (due to movement between the two being free), the X-Ray climb will now originate at the door and skip the junction. The same solution will apply for left-facing doors.

@osse101, two of the left-facing door X-Ray climbs are in heated rooms (Crumble Shaft, Screw Attack Room). Do you happen to have heat frame counts for those?

**Comment by osse101** [comment]
All numbers being energy lost:
400 for screw climb
1000 for crumble climb
Setup starting in a heated room:
50 on successful setup
30 to miss door check
70 to transition and miss doorstuck (both rooms heated)

There's some number fuzziness at the start of the climb to verify you are in the correct door position and then have to menu to xray, as the running stationary jump requires you not be on xray already.  Generally I get 4 damage per xray standup attempt, and these are 1 screen length, and 3 screen length climbs,  I think.

**Comment by fdtaillefer** [comment]
Are the current heat frame counts for X-Ray climbs correct then?

That right-side Screw climb, with 400 energy lost, adds up to 1600 heat frames. But the  left-side full Screw climb, which is twice as long, currently has a value of 800 heat frames (i.e. 200 energy lost).

Is it possible the current heatFrame counts for X-Ray climbs were intended to be energy lost? I'll fix them if so.

**Comment by osse101** [comment]
That seems to be the case.  Reclimbing from GTs door was like 700 energy lost.  And I think I included the setup time in GTs room last time which isn't strictly correct.

**Comment by fdtaillefer** [comment]
Setup time in a separate (potentially heated) room is another issue altogether. I hadn't thought of it, and there's no way to represent it currently. I think it's worth a separate ticket.

We've never had a need to know whether a room is heated until now, since everything just systematically had heat frames. And then Volcano Room throws a big wrench in _that_.

I'll fix the current X-Ray climb heat frames as part of this ticket, at least.

**Comment by fdtaillefer** [comment]
Does this doorstuck method work in water physics? A few of the setups are underwater and will hard require Gravity if not.

**Comment by fdtaillefer** [comment]
Is there a reason you didn't list an X-Ray climb from 4 to 12 in West Ocean?
It's the door from Gravity Suit Room, and I would've expected and X-Ray climb to the top portion of West Ocean to be doable.

But then I also don't know what there is about Landing Site's geometry that prevents X-Ray Climbing. Is it a similar issue?

**Comment by osse101** [comment]
I didn't think about the door exiting gravity.  Just tried it and you get caught on the geometry of the bridge section and can't move up past it. 

For this method wet->wet doesn't work.  wet-> dry shouldn't work because the wet negates your **dashing** spinjump.
There is a double or triple frame perfect way to get wet->wet to work but that's not something I was going to suggest including.

Right facing doors work without gravity using the old tech (Draygon escape xray climb).  But I would assume physics changing through a door wouldn't make it not work.

**Comment by fdtaillefer** [comment]
The issue about setting up in water physics could be represented by needing a 0-length runway on the adjacent node. It will be necessary to make sure all underwater o-length runway require Gravity, and the two morph tunnel transitions must not have a runway.

Down the road, it could be relevant to convert those to https://github.com/miketrethewey/sm-json-data/issues/456

**Comment by fdtaillefer** [comment]
Resolved by #461
