### ISSUE TITLE
Crocomire - Missile capacity requirements

### ISSUE THREAD

**Issue by kjbranch** [miketrethewey/sm-json-data#504]
The strat for killing Crocomire with missiles only requires 10 missiles, as you are able to farm during the fight. However, this strat should only require a 10 missile capacity - if a player currently has 0/10 missiles, they should still be able to defeat him by farming at the beginning of the fight.

**Comment by osse101** [comment]
I'm trying to think of other places that require a specific capacity, and I don't think there are any yet.  GT probably should since the farming is non trivial.  A missile GT strat would just for convenience.  I'll want to look at if farming low health draygon is reasonable too, or if you need 'finish her' amounts of ammo.  
Convenience capacities could become a thing to control difficulty, most bosses say 1 pack = infinite ammo currently.
