### ISSUE TITLE
Shinesparks With Less Energy

### ISSUE THREAD

**Issue by kjbranch** [miketrethewey/sm-json-data#559]
Add a way to represent a minimum amount of energy needed to execute a strat using a shinespark.

In the Landing Site, for example, shinesparking from 4->1 (Gauntlet entrance) requires 154 energy (125 energy loss). But it can be done with a lower maximum health, only requiring 121 energy (92 loss). It is even possible to do it with no energy tanks by running, jumping, and perform a mid-air shinespark.

**Comment by osse101** [comment]
The issue of shinesparking exactly until you've broken through `obstacle` and intentionally stopping there is too messy for my liking, where you would damage down to certain health ranges.

The issue of doing a 154 health spark when you only have 121, but that makes it through `obstacle`  is reasonable.  This could look like `shineSparkFramesRequired(optional)`

The issue of using health conserving movements sounds complicated.  But it is converting `framesRemaining` into less health cost by moving in the direction of the shinespark goal.  `canShineCharge` gets the full 3 seconds so there is room to do a lot.  I could see this looking like a `{Strat}` system with frame cost and requirements.  Or as a `reduceSparkFrameCost` value with an intuitive movement being the expected action (jump with angle held, jump forward and midair spark) and a tech set to enable this value.

**Comment by osse101** [comment]
The example given of entering the gauntlet door of landing site one no etanks is a case worth making work, and it can't be done with simple movements.  A simple straight jump or jump into horizontal spark saves about 10 health.  A more difficult setup including walljumps, or building run speed before sparking can save 20-30 health and can make a big difference.  But then HJB and spacejump get involved for how much can be saved.

It should be possible to take extra possible frames from `comeInCharged` and apply these health saving strats using them.  If a strat requires `42 framesRemaining`, but has a runway providing `150` then you would have time to maneuver a bit, and that's not represented right now.  

I would like to see `angle-down jump: {timerCost: 40 frames, shineFramesSaved: 10}` as a default since its one everyone does. (Tweak the numbers.)  Jump into midair spark seems less value for the difficulty but can still get around the same 40:10 frames value.  

So as not to get crazy with it, and because health values aren't min/maxed, I think a complex movement health saving system would be used sparingly.  Gauntlet entry, main street to the missile pack, everest top door.  But not something like screw attack room where you break the blocks with screw, jump to a ledge, walljump twice and spark to save 20health over a straight jump spark.

I was going to call `extraSparkDistance` -> `excessShinesparkFrames`
`canShineCharge` should have enough timer to do whatever strat is written.
`canComeInCharged` would be calculating `combined runway`->`framesRemaining`->`Health Saving Strat Time Cost`->(`shinesparkFrames` - `excessShinesparkFrames`)

Or we could do `strats:[ "Shinespark", "HardShineSpark"]` which seems more inline with how I picture things.  I'll go with this approach.
