### ISSUE TITLE
Adjust reqs for Double Chamber walljump up left side

### ISSUE THREAD

**Issue by blkerby** [miketrethewey/sm-json-data#988]
This strat seems to be one that people frequently struggle with. Right now with HiJump it's in Map Rando logic in Basic, otherwise Medium, and there's not much lenience (on Basic the logic says it could be done with just 1 tank, on Hard with no tanks). If the player doesn't know what they're doing, it's pretty brutal. A couple examples:

- https://youtu.be/flqjV0FBokU?t=1326
- https://clips.twitch.tv/CrispyWildRamen4Head-3VcGtoIo6pI1OYaM (3rd attempt, after which they started using save states)

Many things can go wrong here: getting fireballed by the Namihe, bonking the Namihe while trying to reach the Kamer, or the Kamer being at the wrong height. I think this strat would also be a good one to make notable: bringing visibility to it with a detailed note could help, since the easier way to do this strat (running under the Kamer to get it to come down) is not very intuitive. 

To get up there optimally (not waiting for the Kamer to come down) I think also requires canDelayedWalljump. Heat frames could probably be tightened in that case.

On Medium settings and lower, I think it should require h_heatProof. So we could just split off the suitless version as a notable and put that in Hard or Very Hard. I guess Hard probably makes more sense, so that it can describe the easier method without the delayed walljump.

**Comment by osse101** [comment]
Traditionally left side double chamber wasn't worth the trouble at very hard level, vanilla map randomizers. With or without hijump.  Wild that its in Basic.

Yeah optimally you delayed walljump off the very bottom of the fune head, but that should only come up if you enter the room in spinjump, otherwise you can lower the kamer.
I've heard killing the Fune helps, but that was in reference to climbing up right side.
